x, y, z = input("Enter three values: ").split()
print("Total number of students: ", x)
print("Number of boys is : ", y)
print("Number of girls is : ", z)
print("First number is {} second number is {} and third number is {} ". format(x,y,z))
